/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.painless;

import java.util.Collection;

/**
 * Built-in {@code @allocates_dynamic} estimators for whitelisted JDK methods and constructors. Each estimator is a
 * {@code public static long} method whose parameters match the annotated target's full Java signature (receiver first for
 * instance methods) and whose result is the <b>total</b> heap cost attributable to the call, including transitive JDK-internal
 * allocations. Estimators are invoked from generated bytecode on the allocation pre-check path, so they must be cheap, must not
 * allocate, and <b>must not throw</b> — even on argument values the annotated call itself would reject (the call's own
 * validation runs after the pre-check). Results are normalized by {@link AllocationGuard#sanitizeEstimate(long)} before being
 * charged, so a huge result trips the limit and a negative one falls back to a conservative constant.
 */
public final class AllocationEstimators {

    private AllocationEstimators() {}

    /**
     * Cost of {@code String.substring(begin, end)}: the result {@code String} plus its backing array of {@code end - begin}
     * chars at 2 bytes each (UTF-16 worst case). An empty or inverted range costs just the wrapper; the real call rejects
     * invalid indices itself after the pre-check.
     */
    public static long substringBytes(String receiver, int begin, int end) {
        long chars = Math.max(0L, (long) end - begin);
        return AllocSizes.STRING_CONCAT_RESULT_OVERHEAD + AllocSizes.mulSat(2L, chars);
    }

    /**
     * Cost of {@code new ArrayList(collection)}: the list wrapper plus a backing {@code Object[]} sized to the source
     * collection. A {@code null} collection costs just the wrapper; the real constructor rejects the {@code null} itself after
     * the pre-check.
     */
    public static long arrayListCollectionBytes(Collection<?> collection) {
        long size = collection == null ? 0 : collection.size();
        return ARRAY_LIST_SHELL_BYTES + AllocSizes.arrayBytes(size, AllocSizes.REFERENCE_SIZE);
    }

    /**
     * Heap cost of an {@code ArrayList} instance itself (header, size/modCount fields, elementData reference), excluding any
     * backing array. Matches the {@code @allocates_constant} value on the no-arg {@code new ArrayList()}, whose backing array
     * is lazily created.
     */
    static final long ARRAY_LIST_SHELL_BYTES = 40;
}
