/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.painless;

import org.elasticsearch.logging.LogManager;
import org.elasticsearch.logging.Logger;

/**
 * Runtime helper for Painless allocation tracking. The per-instance charge-and-check lives on the generated script class's
 * {@link PainlessScript#$checkAllocBytes(long)} override (which bakes in the per-context limit); this helper is called by that
 * override on the rare breach path to log and raise the limit error, keeping the generated bytecode small. Only referenced
 * when tracking is enabled (a positive limit).
 */
public final class AllocationGuard {

    private static final Logger logger = LogManager.getLogger(AllocationGuard.class);

    /**
     * Conservative byte charge substituted when an {@code @allocates_dynamic} estimator misbehaves by returning a negative
     * value. Large enough that a runaway loop of misestimated allocations still trips a sane limit reasonably quickly.
     */
    public static final long ESTIMATE_FALLBACK_BYTES = 4096;

    /** One-time flag so a misbehaving estimator warns once per JVM instead of flooding the log from a hot loop. */
    private static volatile boolean warnedNegativeEstimate = false;

    private AllocationGuard() {}

    /**
     * Normalizes an {@code @allocates_dynamic} estimator's result before it is charged. A negative value signals a buggy
     * estimator: substitute {@link #ESTIMATE_FALLBACK_BYTES} (and {@code WARN} once per JVM). Huge values are clamped to
     * {@code Long.MAX_VALUE / 2}, which still unconditionally trips any configurable limit (bounded at 1gb) without risking
     * overflow of the running total; estimators may return {@code Long.MAX_VALUE} to signal "definitely over any limit".
     * Estimators must not throw; a thrown exception propagates and fails the script.
     */
    public static long sanitizeEstimate(long estimatedBytes) {
        if (estimatedBytes < 0) {
            if (warnedNegativeEstimate == false) {
                warnedNegativeEstimate = true;
                logger.warn(
                    "a Painless allocation estimator returned a negative size [{}]; substituting the conservative fallback of "
                        + "[{}] bytes (this is a bug in the estimator; further occurrences will not be logged)",
                    estimatedBytes,
                    ESTIMATE_FALLBACK_BYTES
                );
            }
            return ESTIMATE_FALLBACK_BYTES;
        }
        return Math.min(estimatedBytes, Long.MAX_VALUE / 2);
    }

    /**
     * Logs a {@code WARN} and throws a {@link PainlessError} describing an allocation that pushed a script over its limit.
     * {@link PainlessError} is an {@link Error}, so it cannot be caught from Painless source. Never returns normally. The
     * specific allocation that crossed the limit is not reported: it is whichever happened to tip the running total, not
     * necessarily the dominant cost, so naming it would mislead more than help.
     *
     * @param attemptedBytes the size of the allocation that tripped the limit
     * @param totalBytes the running total after charging the allocation
     * @param limitBytes the per-context limit
     */
    public static void allocationLimitExceeded(long attemptedBytes, long totalBytes, long limitBytes) {
        logger.warn(
            "Painless script allocation limit exceeded: allocation of [{}] bytes brings running total to [{}] bytes (limit [{}] bytes)",
            attemptedBytes,
            totalBytes,
            limitBytes
        );
        throw new PainlessError(
            "script allocation limit exceeded: allocation of ["
                + attemptedBytes
                + "] bytes brings the running total to ["
                + totalBytes
                + "] bytes, over the limit of ["
                + limitBytes
                + "] bytes"
        );
    }
}
