/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

package org.elasticsearch.painless;

import org.elasticsearch.script.IngestConditionalScript;

import java.util.BitSet;
import java.util.Map;

/**
 * Factory for conditions evaluated from a {@link ConditionProgram} rather than from generated bytecode.
 * <p>
 * There is one instance per condition but only one class, in contrast to the generated path where each
 * condition produces its own script class and its own factory class under its own classloader. The
 * anonymous script below is likewise a single class shared by every condition, so the per-condition cost
 * is the program's arrays on the heap instead of several KB of metaspace.
 * <p>
 * A fresh script instance is still created per execution, exactly as a generated factory does, because the
 * script holds the per-document ctx.
 */
final class ProgramConditionalFactory implements IngestConditionalScript.Factory {

    private final ConditionProgram program;
    private final String name;
    private final String source;

    /**
     * Statement boundaries are used to point at the offending line when a script throws. A recognised
     * condition is a single expression and never appears in the stack trace under
     * {@link WriterConstants#CLASS_NAME}, so {@link PainlessScript#convertToScriptException} never consults
     * this; it is present only to satisfy the interface.
     */
    private static final BitSet NO_STATEMENTS = new BitSet();

    ProgramConditionalFactory(ConditionProgram program, String name, String source) {
        this.program = program;
        this.name = name;
        this.source = source;
    }

    // for testing
    ConditionProgram getProgram() {
        return program;
    }

    @Override
    public IngestConditionalScript newInstance(Map<String, Object> params, Map<String, Object> ctxMap) {
        return new ProgramCondition(params, ctxMap);
    }

    /**
     * Implements {@link PainlessScript} so that a failure is reported as the same {@link
     * org.elasticsearch.script.ScriptException}, carrying the same script name and source, that the
     * generated path produces via its injected try/catch.
     */
    private final class ProgramCondition extends IngestConditionalScript implements PainlessScript {

        ProgramCondition(Map<String, Object> params, Map<String, Object> ctxMap) {
            super(params, ctxMap);
        }

        @Override
        public String getName() {
            return name;
        }

        @Override
        public String getSource() {
            return source;
        }

        @Override
        public BitSet getStatements() {
            return NO_STATEMENTS;
        }

        @Override
        public boolean execute() {
            try {
                return program.execute(getCtx(), getParams());
            } catch (Throwable t) {
                throw convertToScriptException(t, Map.of());
            }
        }
    }
}
